import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import MenuitemF from "@/components/menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <div className="w-11/12 md:w-10/12 mx-auto py-14">
            <div className="flex justify-between items-center">
              <Link href="/">
                <h1 className="text-white">My Ads Portal</h1>
              </Link>
              <div className="lg:flex lg:gap-8  ">
                <MenuitemF />
                <Link href="/login">
                  <span className="text-white font-semibold rounded-lg">
                    Login
                  </span>
                </Link>
              </div>
            </div>
          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}
